backend:
  name: git-gateway
  branch: master

media_folder: src/images
public_folder: /static

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/posts"
    create: true
    slug: "{{slug}}"
    media_folder: ""
    public_folder: ""
    path: "{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          timeFormat: false,
          dateFormat: "MM-DD-YYYY",
          format: "MM-DD-YYYY",
        }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
